import pandas as pd
import json
from datetime import datetime, timedelta
import matplotlib.pyplot as plt


INPUT_DTA_PATH = "data/JudgesBIO_TOUSE.dta"
OUTPUT_JSON_PATH = "data/judge_profiles.json"

df = pd.read_stata(INPUT_DTA_PATH)

header_mapping = {
    "RecessAppoint~1 float": "Recess Appoint 1 Float",
    "RecessAppoint~2 float": "Recess Appoint 2 Float",
    "RecessAppoint~3 float": "Recess Appoint 3 Float",
    "RecessAppoint~4 int": "Recess Appoint 4 Int",
    "RecessAppoint~5 int": "Recess Appoint 5 Int",
    "RecessAppoint~6 int": "Recess Appoint 6 Int",
    "AppointmentDa~1 float": "Appointment Da 1 Float",
    "AppointmentDa~2 float": "Appointment Da 2 Float",
    "AppointmentDa~3 float": "Appointment Da 3 Float",
    "AppointmentDa~4 float": "Appointment Da 4 Float",
    "AppointmentDa~5 int": "Appointment Da 5 Int",
    "AppointmentDa~6 int": "Appointment Da 6 Int",
    "TerminationDa~1 float": "Termination Da 1 Float",
    "TerminationDa~2 float": "Termination Da 2 Float",
    "TerminationDa~3 float": "Termination Da 3 Float",
    "TerminationDa~4 float": "Termination Da 4 Float",
    "TerminationDa~5 int": "Termination Da 5 Int",
    "TerminationDa~6 int": "Termination Da 6 Int",
    "songername": "Songername",
    "courtname1": "Court Name",
    "courtname2": "Court Name (2)",
    "courtname3": "Court Name (3)",
    "courtname4": "Court Name (4)",
    "courtname5": "Court Name (5)",
    "courtname6": "Court Name (6)",
    "x_prot": "X Prot",
    "x_prior_fedj": "X Prior Fedj",
    "x_pros": "X Pros",
    "x_plwpr": "X Plwpr",
    "x_pgovt": "X Pgovt",
    "x_pausa": "X Pausa",
    "x_pusa": "X Pusa",
    "x_pmag": "X Pmag",
    "x_pssc": "X Pssc",
    "x_pslc": "X Pslc",
    "x_plocct": "X Plocct",
    "x_psgo": "X Psgo",
    "x_psg": "X Psg",
    "x_pag": "X Pag",
    "x_pcc": "X Pcc",
    "x_psp": "X Psp",
    "x_pbank": "X Pbank",
    "x_pfedjdge": "X Pfedjdge",
    "x_phouse": "X Phouse",
    "x_pshouse": "X Pshouse",
    "x_psenate": "X Psenate",
    "x_pssenate": "X Pssenate",
    "x_pgov": "X Pgov",
    "x_pmayor": "X Pmayor",
    "x_pccoun": "X Pccoun",
    "x_pada": "X Pada",
    "x_pda": "X Pda",
    "x_pprivate": "X Pprivate",
    "x_pasatty": "X Pasatty",
    "x_psatty": "X Psatty",
    "x_llmsjd": "X Llmsjd",
    "x_aba": "X Aba",
    "x_jew": "X Jew",
    "x_jdpub": "X Jdpub",
    "x_insba": "X Insba",
    "x_black": "X Black",
    "x_bapub": "X Bapub",
    "x_b10s": "X B 10S",
    "x_b20s": "X B 20S",
    "x_b30s": "X B 30S",
    "x_b40s": "X B 40S",
    "x_b50s": "X B 50S",
    "x_nw": "X Nw",
    "x_norel": "X Norel",
    "x_fem": "X Fem",
    "x_unity": "X Unity",
    "x_cath": "X Cath",
    "x_mline": "X Mline",
    "x_evang": "X Evang",
    "x_elev": "X Elev",
    "x_rich": "X Rich",
    "x_crossa": "X Crossa",
    "x_dem": "X Dem",
    "x_repub": "X Repub",
    "x_crossa1": "X Crossa 1",
    "x_crossa2": "X Crossa 2",
    "x_crossa3": "X Crossa 3",
    "x_crossa4": "X Crossa 4",
    "x_crossa5": "X Crossa 5",
    "x_unity1": "X Unity 1",
    "x_unity2": "X Unity 2",
    "x_unity3": "X Unity 3",
    "x_unity4": "X Unity 4",
    "x_unity5": "X Unity 5",
    "x_sdemMaj1": "X Sdem Maj 1",
    "x_srepMaj1": "X Srep Maj 1",
    "x_sdemMaj2": "X Sdem Maj 2",
    "x_srepMaj2": "X Srep Maj 2",
    "x_sdemMaj3": "X Sdem Maj 3",
    "x_srepMaj3": "X Srep Maj 3",
    "x_sdemMaj4": "X Sdem Maj 4",
    "x_srepMaj4": "X Srep Maj 4",
    "x_sdemMaj5": "X Sdem Maj 5",
    "x_srepMaj5": "X Srep Maj 5",
    "x_sdemMaj": "X Sdem Maj",
    "x_srepMaj": "X Srep Maj",
    "x_hdemMaj1": "X Hdem Maj 1",
    "x_hrepMaj1": "X Hrep Maj 1",
    "x_hdemMaj2": "X Hdem Maj 2",
    "x_hrepMaj2": "X Hrep Maj 2",
    "x_hdemMaj3": "X Hdem Maj 3",
    "x_hrepMaj3": "X Hrep Maj 3",
    "x_hdemMaj4": "X Hdem Maj 4",
    "x_hrepMaj4": "X Hrep Maj 4",
    "x_hdemMaj5": "X Hdem Maj 5",
    "x_hrepMaj5": "X Hrep Maj 5",
    "ayear2": "Ayear 2",
    "ayear3": "Ayear 3",
    "ayear4": "Ayear 4",
    "ayear5": "Ayear 5",
    "ayear6": "Ayear 6",
    "ayear": "Ayear",
    "birthday": "Birth day",
    "birthmonth": "Birth month",
    "birthyear": "Birth year",
    "deathmonth": "Death month",
    "deathday": "Death day",
    "deathyear": "Death year",
    "appres": "Appres",
    "judgeidentifi~r int": "Judgeidentifir Int",
    "JudgeAssigned~1 str16": "Judge Assigned 1 Str 16",
    "JudgeAssigned~2 str16": "Judge Assigned 2 Str 16",
    "JudgeAssigned~3 str16": "Judge Assigned 3 Str 16",
    "JudgeAssigned~4 str15": "Judge Assigned 4 Str 15",
    "JudgeAssigned~5 str15": "Judge Assigned 5 Str 15",
    "JudgeAssigned~6 str15": "Judge Assigned 6 Str 15",
    "judgelastname": "Judge Last Name",
    "judgefirstname": "Judge First Name",
    "judgemiddlename str24": "Judgemiddlename Str 24",
    "suffix": "Suffix",
    "courttype1": "Court Type",
    "courttype2": "Court Type (2)",
    "courttype3": "Court Type (3)",
    "courttype4": "Court Type (4)",
    "courttype5": "Court Type (5)",
    "courttype6": "Court Type (6)",
    "Circuitjudge1": "Circuitjudge 1",
    "Circuitjudge2": "Circuitjudge 2",
    "Circuitjudge3": "Circuitjudge 3",
    "Circuitjudge4": "Circuitjudge 4",
    "Circuitjudge5": "Circuitjudge 5",
    "Circuitjudge6": "Circuitjudge 6",
    "SeatState1": "Seat State 1",
    "SeatState2": "Seat State 2",
    "SeatState3": "Seat State 3",
    "SeatState4": "Seat State 4",
    "SeatState5": "Seat State 5",
    "SeatState6": "Seat State 6",
    "retirementfro~1 str10": "Retirementfro 1 Str 10",
    "retirementfro~2 str10": "Retirementfro 2 Str 10",
    "retirementfro~3 str10": "Retirementfro 3 Str 10",
    "retirementfro~4 str10": "Retirementfro 4 Str 10",
    "retirementfro~5 str10": "Retirementfro 5 Str 10",
    "retirementfro~6 str10": "Retirementfro 6 Str 10",
    "unity1": "Unity 1",
    "unity2": "Unity 2",
    "unity3": "Unity 3",
    "unity4": "Unity 4",
    "unity5": "Unity 5",
    "unity": "Unity",
    "unityi": "Unityi",
    "unityo": "Unityo",
    "sdem1": "1 sdem",
    "sdem2": "2 sdem",
    "sdem3": "3 sdem",
    "sdem4": "4 sdem",
    "sdem5": "5 sdem",
    "sdem": "Sdem",
    "sdem6": "6 sdem",
    "srep1": "1 srep",
    "srep2": "2 srep",
    "srep3": "3 srep",
    "srep4": "4 srep",
    "srep5": "5 srep",
    "srep": "Srep",
    "srep6": "6 srep",
    "sother1": "1 sother",
    "sother2": "2 sother",
    "sother3": "3 sother",
    "sother4": "4 sother",
    "sother5": "5 sother",
    "sother6": "6 sother",
    "sother": "Sother",
    "hdem1": "1 hdem",
    "hdem2": "2 hdem",
    "hdem3": "3 hdem",
    "hdem4": "4 hdem",
    "hdem5": "5 hdem",
    "hdem6": "6 hdem",
    "hdem": "Hdem",
    "hrep1": "1 hrep",
    "hrep2": "2 hrep",
    "hrep3": "3 hrep",
    "hrep4": "4 hrep",
    "hrep5": "5 hrep",
    "hrep6": "6 hrep",
    "hrep": "Hrep",
    "hother1": "1 hother",
    "hother2": "2 hother",
    "hother3": "3 hother",
    "hother4": "4 hother",
    "hother5": "5 hother",
    "hother6": "6 hother",
    "hother": "Hother",
    "congresi1": "1 congresi",
    "congresi2": "2 congresi",
    "congresi3": "3 congresi",
    "congresi4": "4 congresi",
    "congresi5": "5 congresi",
    "congresi6": "6 congresi",
    "congresi": "Congresi",
    "birthdate": "Birthdate",
    "SenatesCount1": "1 SenatesCount",
    "SenatesCount2": "2 SenatesCount",
    "SenatesCount3": "3 SenatesCount",
    "SenatesCount4": "4 SenatesCount",
    "SenatesCount5": "5 SenatesCount",
    "SenatesCount6": "6 SenatesCount",
    "dateaschiefj~n1 int": "Dateaschiefjn 1 Int",
    "dateaschiefj~n2 int": "Dateaschiefjn 2 Int",
    "dateaschiefj~n3 int": "Dateaschiefjn 3 Int",
    "dateaschiefj~n4 int": "Dateaschiefjn 4 Int",
    "dateaschiefj~n5 int": "Dateaschiefjn 5 Int",
    "dateaschiefj~n6 byte": "Dateaschiefjn 6 Byte",
    "presidentname1": "President name",
    "presidentname2": "President name (2)",
    "pres1": "Pres 1",
    "pres2": "Pres 2",
    "pres3": "Pres 3",
    "pres4": "Pres 4",
    "pres5": "Pres 5",
    "pres6": "Pres 6",
    "presidentname3": "President name (3)",
    "presidentname4": "President name (4)",
    "presidentname5": "President name (5)",
    "presidentname6": "President name (6)",
    "pres": "Pres",
    "prespty": "Prespty",
    "seconddateas~n1 int": "Seconddateasn 1 Int",
    "seconddateas~n2 byte": "Seconddateasn 2 Byte",
    "seconddateas~n3 byte": "Seconddateasn 3 Byte",
    "seconddateas~n4 byte": "Seconddateasn 4 Byte",
    "seconddateas~n5 byte": "Seconddateasn 5 Byte",
    "seconddateas~n6 byte": "Seconddateasn 6 Byte",
    "Nominationdate1 float": "Nominationdate 1 Float",
    "Nominationdate2 float": "Nominationdate 2 Float",
    "Nominationdate3 float": "Nominationdate 3 Float",
    "Nominationdate4 float": "Nominationdate 4 Float",
    "Nominationdate5 int": "Nominationdate 5 Int",
    "SenateConfirm~1 float": "Senate Confirm 1 Float",
    "SenateConfirm~2 float": "Senate Confirm 2 Float",
    "SenateConfirm~3 float": "Senate Confirm 3 Float",
    "SenateConfirm~4 float": "Senate Confirm 4 Float",
    "SenateConfirm~5 int": "Senate Confirm 5 Int",
    "SenateConfirm~6 int": "Senate Confirm 6 Int",
    "senatevoicevo~1 str3": "Senatevoicevo 1 Str 3",
    "senatevoicevo~2 str3": "Senatevoicevo 2 Str 3",
    "senatevoicevo~3 str3": "Senatevoicevo 3 Str 3",
    "senatevoicevo~4 str3": "Senatevoicevo 4 Str 3",
    "senatevoicevo~5 str3": "Senatevoicevo 5 Str 3",
    "senatevoicevo~6 str3": "Senatevoicevo 6 Str 3",
    "senatevoteaye~1 str6": "Senatevoteaye 1 Str 6",
    "senatevoteaye~2 str6": "Senatevoteaye 2 Str 6",
    "senatevoteaye~3 str5": "Senatevoteaye 3 Str 5",
    "senatevoteaye~4 str1": "Senatevoteaye 4 Str 1",
    "senatevoteaye~5 str1": "Senatevoteaye 5 Str 1",
    "senatevoteaye~6 str1": "Senatevoteaye 6 Str 1",
    "Committeeact~e1 float": "Committeeacte 1 Float",
    "Committeeact~e2 float": "Committeeacte 2 Float",
    "Committeeact~e3 float": "Committeeacte 3 Float",
    "Committeeact~e4 int": "Committeeacte 4 Int",
    "Committeeact~e5 int": "Committeeacte 5 Int",
    "Committeeact~e6 int": "Committeeacte 6 Int",
    "Degree1": "Degree 1",
    "Degree2": "Degree 2",
    "Degree3": "Degree 3",
    "Degree4": "Degree 4",
    "Degree5": "Degree 5",
    "degreeyear1": "Degree year",
    "degreeyear2": "Degree year (2)",
    "degreeyear3": "Degree year (3)",
    "degreeyear4": "Degree year (4)",
    "degreeyear5": "Degree year (5)",
    "PublicSchool1": "Public School 1",
    "PublicSchool2": "Public School 2",
    "PublicSchool3": "Public School 3",
    "PublicSchool4": "Public School 4",
    "PublicSchool5": "Public School 5",
    "Committeeact~n1 byte": "Committeeactn 1 Byte",
    "Committeeact~n2 byte": "Committeeactn 2 Byte",
    "Committeeact~n3 byte": "Committeeactn 3 Byte",
    "Committeeact~n4 byte": "Committeeactn 4 Byte",
    "Committeeact~n5 byte": "Committeeactn 5 Byte",
    "Committeeact~n6 byte": "Committeeactn 6 Byte",
    "abarating1": "ABA Rating",
    "abarating2": "ABA Rating (2)",
    "aba1": "Aba 1",
    "aba2": "Aba 2",
    "aba3": "Aba 3",
    "aba4": "Aba 4",
    "aba5": "Aba 5",
    "aba6": "Aba 6",
    "abarating3": "ABA Rating (3)",
    "abarating4": "ABA Rating (4)",
    "abarating5": "ABA Rating (5)",
    "abarating6": "ABA Rating (6)",
    "aba": "Aba",
    "abamin": "Abamin",
    "ageon1": "Ageon 1",
    "ageon2": "Ageon 2",
    "ageon3": "Ageon 3",
    "ageon4": "Ageon 4",
    "ageon5": "Ageon 5",
    "ageon6": "Ageon 6",
    "ageon": "Ageon",
    "left1": "Left 1",
    "left2": "Left 2",
    "left3": "Left 3",
    "left4": "Left 4",
    "left5": "Left 5",
    "left6": "Left 6",
    "vicelastnamep~1 str17": "Vicelastnamep 1 Str 17",
    "vicelastnamep~2 str15": "Vicelastnamep 2 Str 15",
    "vicelastnamep~3 str11": "Vicelastnamep 3 Str 11",
    "vicelastnamep~4 str7": "Vicelastnamep 4 Str 7",
    "vicelastnamep~5 str6": "Vicelastnamep 5 Str 6",
    "vicelastnamep~6 str6": "Vicelastnamep 6 Str 6",
    "vicefirstname~1 str22": "Vicefirstname 1 Str 22",
    "vicefirstname~2 str22": "Vicefirstname 2 Str 22",
    "vicefirstname~3 str15": "Vicefirstname 3 Str 15",
    "vicefirstname~4 str12": "Vicefirstname 4 Str 12",
    "vicefirstname~5 str12": "Vicefirstname 5 Str 12",
    "vicefirstname~6 str12": "Vicefirstname 6 Str 12",
    "hearings1": "Hearings",
    "hearings2": "Hearings (2)",
    "hearings3": "Hearings (3)",
    "hearings4": "Hearings (4)",
    "hearings5": "Hearings (5)",
    "hearings6": "Hearings (6)",
    "reportnumber": "Report number",
    "reportnumber2": "Report number (2)",
    "reportnumber3": "Report number (3)",
    "reportnumber4": "Report number (4)",
    "reportnumber5": "Report number (5)",
    "reportnumber6": "Report number (6)",
    "authorization~1 str14": "Authorization 1 Str 14",
    "authorization~2 str14": "Authorization 2 Str 14",
    "authorization~3 str13": "Authorization 3 Str 13",
    "authorization~4 str13": "Authorization 4 Str 13",
    "authorization~5 str12": "Authorization 5 Str 12",
    "authorization~6 str1": "Authorization 6 Str 1",
    "placeofbirthc~y str36": "Placeofbirthcy Str 36",
    "placeofbirths~e str18": "Placeofbirthse Str 18",
    "placeofdeathc~y str37": "Placeofdeathcy Str 37",
    "placeofdeaths~e str11": "Placeofdeathse Str 11",
    "deathdate": "Deathdate",
    "race": "Race",
    "gender": "Gender",
    "BirthState": "Birth State",
    "pfedjdge": "Pfedjdge",
    "pfjdget": "Pfjdget",
    "employmenttex~d str1421": "Employmenttexd Str 1421",
    "pssc": "Pssc",
    "pslc": "Pslc",
    "plocct": "Plocct",
    "psjdget": "Psjdget",
    "psgo": "Psgo",
    "psg": "Psg",
    "pago": "Pago",
    "pag": "Pag",
    "pcc": "Pcc",
    "psp": "Psp",
    "pasatty": "Pasatty",
    "religion": "Religion",
    "party": "Party",
    "dateaschiefj~d1 int": "Dateaschiefjd 1 Int",
    "dateaschiefj~d2 int": "Dateaschiefjd 2 Int",
    "dateaschiefj~d3 int": "Dateaschiefjd 3 Int",
    "dateaschiefj~d4 int": "Dateaschiefjd 4 Int",
    "dateaschiefj~d5 int": "Dateaschiefjd 5 Int",
    "dateaschiefj~d6 byte": "Dateaschiefjd 6 Byte",
    "seconddateas~d1 int": "Seconddateasd 1 Int",
    "seconddateas~d2 byte": "Seconddateasd 2 Byte",
    "seconddateas~d3 byte": "Seconddateasd 3 Byte",
    "seconddateas~d4 byte": "Seconddateasd 4 Byte",
    "seconddateas~d5 byte": "Seconddateasd 5 Byte",
    "seconddateas~d6 byte": "Seconddateasd 6 Byte",
    "v18": "Judge Identification Number",
    "renominatingp~e str15": "Renominatingpe Str 15",
    "partyaffiliat~r str10": "Partyaffiliatr Str 10",
    "referraldater~o str10": "Referraldatero Str 10",
    "v47": "Judge Identification Number",
    "renominatingp~2 byte": "Renominatingp 2 Byte",
    "v53": "Party Affiliation of Renominating President",
    "v60": "referral date (referral to Judicial",
    "v76": "Judge Identification Number",
    "renominatingp~3 byte": "Renominatingp 3 Byte",
    "v82": "Party Affiliation of Renominating President",
    "v89": "referral date (referral to Judicial",
    "v105": "Judge Identification Number",
    "renominatingp~4 byte": "Renominatingp 4 Byte",
    "v111": "Party Affiliation of Renominating President",
    "v118": "referral date (referral to Judicial",
    "v134": "Judge Identification Number",
    "renominatingp~5 byte": "Renominatingp 5 Byte",
    "v140": "Party Affiliation of Renominating President",
    "v147": "referral date (referral to Judicial",
    "v163": "Judge Identification Number",
    "renominatingp~6 byte": "Renominatingp 6 Byte",
    "v170": "Party Affiliation of Renominating President",
    "v176": "referral date (referral to Judicial",
    "bankruptcyand~e str464": "Bankruptcyande Str 464",
    "updatemerge": "_merge",
    "pname": "Pname",
    "id": "Id",
    "yearb": "Yearb",
    "yeard": "Yeard",
    "state": "State",
    "city": "City",
    "circuit_judge": "Judge's circuit in Auburn dataset",
    "elevate": "Elevate",
    "pleftsum": "Pleftsum",
    "boom": "Boom",
    "crossa": "Crossa",
    "crossl": "Crossl",
    "mrespty": "Mrespty",
    "dummy": "Dummy",
    "ids": "Ids",
    "csb": "Csb",
    "ba": "Ba",
    "bast": "Bast",
    "bapp": "Bapp",
    "ls": "Ls",
    "lsst": "Lsst",
    "jdpp": "Jdpp",
    "graddeg1": "Graddeg 1",
    "graddeg2": "Graddeg 2",
    "graddeg3": "Graddeg 3",
    "poutsjge": "Poutsjge",
    "pausa": "Pausa",
    "pusa": "Pusa",
    "paag": "Paag",
    "pspros": "Pspros",
    "pmag": "Pmag",
    "pbj": "Pbj",
    "pcab": "Pcab",
    "pcabdept": "Pcabdept",
    "pscab": "Pscab",
    "pscabdpt": "Pscabdpt",
    "pindreg1": "Pindreg 1",
    "preg1": "Preg 1",
    "pindreg2": "Pindreg 2",
    "preg2": "Preg 2",
    "pindreg3": "Pindreg 3",
    "preg3": "Preg 3",
    "pindreg4": "Pindreg 4",
    "preg4": "Preg 4",
    "pindreg5": "Pindreg 5",
    "preg5": "Preg 5",
    "phouse": "Phouse",
    "psenate": "Psenate",
    "pgov": "Pgov",
    "pssenate": "Pssenate",
    "pshouse": "Pshouse",
    "pmayor": "Pmayor",
    "pccoun": "Pccoun",
    "pccom": "Pccom",
    "pda": "Pda",
    "plother": "Plother",
    "plotherl": "Plotherl",
    "pgovt": "Pgovt",
    "plawprof": "Plawprof",
    "pprivate": "Pprivate",
    "prevpos": "Prevpos",
    "pmagis": "Pmagis",
    "pcomct": "Pcomct",
    "pdat": "Pdat",
    "pada": "Pada",
    "pbank": "Pbank",
    "pterr": "Pterr",
    "pcustom": "Pcustom",
    "statecab": "Statecab",
    "age": "Age",
    "extra1": "Extra 1",
    "extra2": "Extra 2",
    "extra3": "Extra 3",
    "extra4": "Extra 4",
    "amon": "Amon",
    "___l": "L",
    "___j": "J",
    "___char": "Char",
    "pos1": "Pos 1",
    "pos1yrs": "Pos 1Yrs",
    "pos2": "Pos 2",
    "pos2yrs": "Pos 2Yrs",
    "pos3": "Pos 3",
    "pos3yrs": "Pos 3Yrs",
    "pos4": "Pos 4",
    "pos4yrs": "Pos 4Yrs",
    "pos5": "Pos 5",
    "pos5yrs": "Pos 5Yrs",
    "pos6": "Pos 6",
    "pos6yrs": "Pos 6Yrs",
    "pos7": "Pos 7",
    "pos7yrs": "Pos 7Yrs",
    "pos8": "Pos 8",
    "pos8yrs": "Pos 8Yrs",
    "pos9": "Pos 9",
    "pos9yrs": "Pos 9Yrs",
    "pos10": "Pos 10",
    "pos10yrs": "Pos 10Yrs",
    "pos11": "Pos 11",
    "pos11yrs": "Pos 11Yrs",
    "pos12": "Pos 12",
    "pos12yrs": "Pos 12Yrs",
    "pos13": "Pos 13",
    "pos13yrs": "Pos 13Yrs",
    "pos14": "Pos 14",
    "pos14yrs": "Pos 14Yrs",
    "pos15": "Pos 15",
    "pos15yrs": "Pos 15Yrs",
    "type": "Type",
    "pred": "Pred",
    "recdatem": "Recdatem",
    "recdatey": "Recdatey",
    "reccon": "Reccon",
    "extra5": "Extra 5",
    "assets": "Assets",
    "liable": "Liable",
    "add1": "Add 1",
    "seatno": "Seatno",
    "success": "Success",
    "seatno2": "Seatno 2",
    "pseatno": "Pseatno",
    "lsuc": "Lsuc",
    "ls2": "Ls 2",
    "ls3": "Ls 3",
    "lp": "Lp",
    "lp2": "Lp 2",
    "lp3": "Lp 3",
    "ls1": "Ls 1",
    "count": "Count",
    "seatno4": "Seatno 4",
    "pseatno4": "Pseatno 4",
    "sseatno4": "Sseatno 4",
    "seatno3": "Seatno 3",
    "pseatno3": "Pseatno 3",
    "sseatno3": "Sseatno 3",
    "lsuc2": "Lsuc 2",
    "pseatno2": "Pseatno 2",
    "sseatno2": "Sseatno 2",
    "sseatno": "Sseatno",
    "sids": "Sids",
    "tids": "Tids",
    "samon": "Samon",
    "sayear": "Sayear",
    "tamon": "Tamon",
    "tayear": "Tayear",
    "yearj": "Yearj",
    "dsen": "Dsen",
    "rsen": "Rsen",
    "dhouse": "Dhouse",
    "rhouse": "Rhouse",
    "dal": "Dal",
    "dak": "Dak",
    "daz": "Daz",
    "dar": "Dar",
    "dca": "Dca",
    "dco": "Dco",
    "dct": "Dct",
    "dde": "Dde",
    "dfl": "Dfl",
    "dga": "Dga",
    "dhi": "Dhi",
    "did": "Did",
    "dil": "Dil",
    "din": "Din",
    "dio": "Dio",
    "dks": "Dks",
    "dky": "Dky",
    "dla": "Dla",
    "dme": "Dme",
    "dmd": "Dmd",
    "dma": "Dma",
    "dmi": "Dmi",
    "dmn": "Dmn",
    "dms": "Dms",
    "dmo": "Dmo",
    "dmt": "Dmt",
    "dne": "Dne",
    "dnv": "Dnv",
    "dnh": "Dnh",
    "dnj": "Dnj",
    "dnm": "Dnm",
    "dny": "Dny",
    "dnc": "Dnc",
    "dnd": "Dnd",
    "doh": "Doh",
    "dok": "Dok",
    "dor": "Dor",
    "dpa": "Dpa",
    "dri": "Dri",
    "dsc": "Dsc",
    "dsd": "Dsd",
    "dtn": "Dtn",
    "dtx": "Dtx",
    "dut": "Dut",
    "dvt": "Dvt",
    "dva": "Dva",
    "dwa": "Dwa",
    "dwv": "Dwv",
    "dwi": "Dwi",
    "dwy": "Dwy",
    "source1": "Source 1",
    "source2": "Source 2",
    "courtesy": "Courtesy",
    "appage": "Appage",
    "sseatno5": "Sseatno 5",
    "sseatno6": "Sseatno 6",
    "pname2": "Pname 2",
    "pname3": "Pname 3",
    "pname4": "Pname 4",
    "dcother": "Dcother",
    "uporoutt": "Uporoutt",
    "senmaj": "Senmaj",
    "senmin": "Senmin",
    "yeari": "Yeari",
    "yearc": "Yearc",
    "congress": "Congress",
    "e1": "E 1",
    "e2": "E 2",
    "e3": "E 3",
    "e4": "E 4",
    "e5": "E 5",
    "e6": "E 6",
    "yearo": "Yearo",
    "congreso": "Congreso",
    "recess": "Recess",
    "networth": "Networth",
    "agego": "Agego",
    "service": "Service",
    "name_x": "Name X",
    "lastname": "Lastname",
    "name_x2": "Name X 2",
    "name_x3": "Name X 3",
    "firstname": "Firstname",
    "middlename": "Middlename",
    "name_original": "Name Original",
    "songer_code": "Songer Code",
    "dct_ayear": "Dct Ayear",
    "appt": "Appt",
    "temp": "Temp",
    "trans": "Trans",
    "dsenate": "Dsenate",
    "rsenate": "Rsenate",
    "fhouse": "Fhouse",
    "fsenate": "Fsenate",
    "drhouse": "Drhouse",
    "drsenate": "Drsenate",
    "whouse": "Whouse",
    "wsenate": "Wsenate",
    "nrhouse": "Nrhouse",
    "nrsenate": "Nrsenate",
    "dsens": "Dsens",
    "rsens": "Rsens",
    "seatno5": "Seatno 5",
    "pseatno5": "Pseatno 5",
    "tperm": "Tperm",
    "multiple": "Multiple",
    "amon2": "Amon 2",
    "dct_ayear2": "Dct Ayear 2",
    "monl2": "Monl 2",
    "dct_yearl2": "Dct Yearl 2",
    "amon3": "Amon 3",
    "dct_ayear3": "Dct Ayear 3",
    "monl3": "Monl 3",
    "dct_yearl3": "Dct Yearl 3",
    "amon4": "Amon 4",
    "dct_ayear4": "Dct Ayear 4",
    "monl4": "Monl 4",
    "dct_yearl4": "Dct Yearl 4",
    "amon5": "Amon 5",
    "dct_ayear5": "Dct Ayear 5",
    "monl5": "Monl 5",
    "dct_yearl5": "Dct Yearl 5",
    "fsens": "Fsens",
    "drsens": "Drsens",
    "wsens": "Wsens",
    "nrsens": "Nrsens",
    "osens": "Osens",
    "extraf1": "Extraf 1",
    "extraf2": "Extraf 2",
    "extraf3": "Extraf 3",
    "extraf4": "Extraf 4",
    "extraf5": "Extraf 5",
    "extraf6": "Extraf 6",
    "extraf7": "Extraf 7",
    "extraf8": "Extraf 8",
    "extraf9": "Extraf 9",
    "extraf10": "Extraf 10",
    "extraf11": "Extraf 11",
    "extraf12": "Extraf 12",
    "extraf13": "Extraf 13",
    "extraf14": "Extraf 14",
    "extraf15": "Extraf 15",
    "extraf16": "Extraf 16",
    "extraf17": "Extraf 17",
    "extraf18": "Extraf 18",
    "extraf19": "Extraf 19",
    "extraf20": "Extraf 20",
    "extra6": "Extra 6",
    "extra7": "Extra 7",
    "extra8": "Extra 8",
    "extra9": "Extra 9",
    "extra10": "Extra 10",
    "extra11": "Extra 11",
    "extra12": "Extra 12",
    "extra13": "Extra 13",
    "extra14": "Extra 14",
    "extra15": "Extra 15",
    "extra16": "Extra 16",
    "extra17": "Extra 17",
    "extra18": "Extra 18",
    "extra19": "Extra 19",
    "extra20": "Extra 20",
    "extra21": "Extra 21",
    "extra22": "Extra 22",
    "extra23": "Extra 23",
    "extra24": "Extra 24",
    "extra25": "Extra 25",
    "dct_yeari": "Dct Yeari",
    "dct_yearc": "Dct Yearc",
    "dct_yearo": "Dct Yearo",
    "e7": "E 7",
    "e8": "E 8",
    "cityb": "Cityb",
    "badeg": "Badeg",
    "bastate": "Bastate",
    "bastatus": "Bastatus",
    "jddeg": "Jddeg",
    "jdstate": "Jdstate",
    "jdstatus": "Jdstatus",
    "grad1": "Grad 1",
    "grad2": "Grad 2",
    "bank": "Bank",
    "terr": "Terr",
    "sscjudge": "Sscjudge",
    "slcjudge": "Slcjudge",
    "lcjudge": "Lcjudge",
    "dct_slyears": "Dct Slyears",
    "ausatty": "Ausatty",
    "usatty": "Usatty",
    "mag": "Mag",
    "sgoff": "Sgoff",
    "sgenl": "Sgenl",
    "agenoff": "Agenoff",
    "subcabj": "Subcabj",
    "agen": "Agen",
    "counse": "Counse",
    "spros": "Spros",
    "subcab": "Subcab",
    "subcabd": "Subcabd",
    "cabsec": "Cabsec",
    "csdept": "Csdept",
    "iragency": "Iragency",
    "iraid": "Iraid",
    "misc1": "Misc 1",
    "misc2": "Misc 2",
    "misc3": "Misc 3",
    "house": "House",
    "senate": "Senate",
    "lhouse": "Lhouse",
    "uhouse": "Uhouse",
    "gov": "Gov",
    "scab": "Scab",
    "scabdept": "Scabdept",
    "mayor": "Mayor",
    "council": "Council",
    "ccom": "Ccom",
    "asatty": "Asatty",
    "satty": "Satty",
    "ada": "Ada",
    "datty": "Datty",
    "localad": "Localad",
    "localow": "Localow",
    "lawprof": "Lawprof",
    "private": "Private",
    "cextra1": "Cextra 1",
    "cextra2": "Cextra 2",
    "cextra3": "Cextra 3",
    "cextra4": "Cextra 4",
    "cextra5": "Cextra 5",
    "cextra6": "Cextra 6",
    "cextra7": "Cextra 7",
    "cextra8": "Cextra 8",
    "mickey": "Mickey",
    "subcabdj": "Subcabdj",
    "counsel": "Counsel",
    "templeg": "Templeg",
    "juris1": "Juris 1",
    "juris1t": "Juris 1T",
    "juris2": "Juris 2",
    "juris2t": "Juris 2T",
    "psatty": "Psatty",
    "state2": "State 2",
    "recdate": "Recdate",
    "dct_yearl_final int": "Dct Yearl Final Int",
    "_merge_dctj": "_merge",
    "firstinitial": "Firstinitial",
    "degree": "Degree",
    "degree_law": "Degree Law",
    "degree_other": "Degree Other",
    "military": "Military",
    "electedoffice": "elected office",
    "priorjudicial~s str3": "Priorjudicials Str 3",
    "othergovtjob": "other govt job",
    "_merge_judges~o byte": "Merge Judgeso Byte",
    "_merge_judges~n byte": "Merge Judgesn Byte",
    "MergeAuburnBIO": "_merge",
    "year": "Year",
    "mergeUpdate": "_merge",
    "yearl3": "Yearl 3",
    "yearl4": "Yearl 4",
    "yearl5": "Yearl 5",
    "slyears": "Slyears",
    "mergeUpdateDi~t byte": "Merge Update Dit Byte",
    "merge": "_merge",
    "mergeH": "_merge",
    "_merge": "Merge",
    "employmenttex~p str1421": "Employmenttexp Str 1421",
    "N": "N",
    "YearsAsDistri~e byte": "Years As Distrie Byte",
    "cityOfResidence str23": "City Of Residence Str 23",
    "StateOfReside~e str3": "State Of Residee Str 3",
    "ResidenceCity": "Residence City",
    "district1": "District 1",
    "district2": "District 2",
    "district3": "District 3",
    "district4": "District 4",
    "district5": "District 5",
    "district6": "District 6",
    "nominationdat~6 byte": "Nominationdat 6 Byte",
    "commissiondate1 str10": "Commissiondate 1 Str 10",
    "commissiondate2 str10": "Commissiondate 2 Str 10",
    "commissiondate3 str10": "Commissiondate 3 Str 10",
    "senatevotedat~1 str10": "Senatevotedat 1 Str 10",
    "committeeact~e1 str10": "Committeeacte 1 Str 10",
    "senatevotedat~2 str10": "Senatevotedat 2 Str 10",
    "committeeact~e2 str10": "Committeeacte 2 Str 10",
    "senatevotedat~3 str10": "Senatevotedat 3 Str 10",
    "senatevotedat~4 str10": "Senatevotedat 4 Str 10",
    "committeeact~e4 str10": "Committeeacte 4 Str 10",
    "dateoftermina~1 str10": "Dateoftermina 1 Str 10",
    "dateoftermina~2 str10": "Dateoftermina 2 Str 10",
    "genderNew": "Gender",
    "raceorethnicity str20": "Raceorethnicity Str 20",
    "partyaffiliat~1 str23": "Partyaffiliat 1 Str 23",
    "nominationdat~1 str10": "Nominationdat 1 Str 10",
    "recessappoint~1 str10": "Recessappoint 1 Str 10",
    "committeeact~n1 str31": "Committeeactn 1 Str 31",
    "terminationsp~1 str40": "Terminationsp 1 Str 40",
    "partyaffiliat~2 str23": "Partyaffiliat 2 Str 23",
    "nominationdat~2 str10": "Nominationdat 2 Str 10",
    "recessappoint~2 str10": "Recessappoint 2 Str 10",
    "committeeact~n2 str31": "Committeeactn 2 Str 31",
    "terminationsp~2 str40": "Terminationsp 2 Str 40",
    "partyaffiliat~3 str23": "Partyaffiliat 3 Str 23",
    "nominationdat~3 str10": "Nominationdat 3 Str 10",
    "recessappoint~3 str10": "Recessappoint 3 Str 10",
    "committeeact~n3 str31": "Committeeactn 3 Str 31",
    "committeeact~e3 str10": "Committeeacte 3 Str 10",
    "dateoftermina~3 str10": "Dateoftermina 3 Str 10",
    "terminationsp~3 str40": "Terminationsp 3 Str 40",
    "partyaffiliat~4 str23": "Partyaffiliat 4 Str 23",
    "nominationdat~4 str10": "Nominationdat 4 Str 10",
    "recessappoint~4 str10": "Recessappoint 4 Str 10",
    "committeeact~n4 str28": "Committeeactn 4 Str 28",
    "commissiondate4 str10": "Commissiondate 4 Str 10",
    "dateoftermina~4 str10": "Dateoftermina 4 Str 10",
    "terminationsp~4 str32": "Terminationsp 4 Str 32",
    "partyaffiliat~5 str12": "Partyaffiliat 5 Str 12",
    "nominationdat~5 str10": "Nominationdat 5 Str 10",
    "recessappoint~5 str10": "Recessappoint 5 Str 10",
    "committeeact~n5 str28": "Committeeactn 5 Str 28",
    "committeeact~e5 str10": "Committeeacte 5 Str 10",
    "senatevotedat~5 str10": "Senatevotedat 5 Str 10",
    "commissiondate5 str10": "Commissiondate 5 Str 10",
    "dateoftermina~5 str10": "Dateoftermina 5 Str 10",
    "terminationsp~5 str10": "Terminationsp 5 Str 10",
    "partyaffiliat~6 str10": "Partyaffiliat 6 Str 10",
    "recessappoint~6 str10": "Recessappoint 6 Str 10",
    "committeeact~n6 str28": "Committeeactn 6 Str 28",
    "committeeact~e6 str10": "Committeeacte 6 Str 10",
    "senatevotedat~6 str10": "Senatevotedat 6 Str 10",
    "commissiondate6 str10": "Commissiondate 6 Str 10",
    "dateoftermina~6 str10": "Dateoftermina 6 Str 10",
    "terminationsp~6 str5": "Terminationsp 6 Str 5",
    "nameofschool1": "Name of School",
    "degree1": "Degree",
    "nameofschool2": "Name of School (2)",
    "degree2": "Degree (2)",
    "nameofschool3": "Name of School (3)",
    "degree3": "Degree (3)",
    "nameofschool4": "Name of School (4)",
    "degree4": "Degree (4)",
    "nameofschool5": "Name of School (5)",
    "degree5": "Degree (5)",
    "appres1": "Appres 1",
    "appres2": "Appres 2",
    "appres3": "Appres 3",
    "appres4": "Appres 4",
    "appres5": "Appres 5",
    "appres6": "Appres 6",
    "ayear1": "Ayear 1",
}

## ANALYSIS
df.to_json(OUTPUT_JSON_PATH, orient="records", indent=2)
print(f"Saved cleaned JSON to {OUTPUT_JSON_PATH}")

with open(OUTPUT_JSON_PATH, 'r') as f:
    data = json.load(f)